extension StarterCatalog {
    static let expandedEntries: [CommandEntry] = [
        entry("Описание ресурса", "kubectl describe <resource> <name> -n <namespace>", .kubernetes,
              ["describe", "debug"], "Показывает состояние, события и параметры ресурса.",
              "Describe объединяет спецификацию, текущее состояние и связанные события. Часто это первый шаг при Pending, CrashLoopBackOff или ошибках scheduling.",
              ["kubectl describe pod api-7d9c -n production"], bundledVersion: 2),
        entry("Выполнить команду в контейнере", "kubectl exec -it <pod> -n <namespace> -- <command>", .kubernetes,
              ["exec", "shell"], "Запускает процесс внутри работающего контейнера.",
              "Разделитель -- отделяет аргументы kubectl от запускаемой команды. Для нескольких контейнеров укажите -c. Образ может не содержать shell.",
              ["kubectl exec -it api-7d9c -n production -c api -- sh"], bundledVersion: 2),
        entry("События по времени", "kubectl get events -A --sort-by=.metadata.creationTimestamp", .kubernetes,
              ["events", "debug"], "Сортирует события кластера от старых к новым.",
              "События помогают найти ошибки образов, probes, volumes и scheduler. Старые события удаляются кластером, поэтому проверяйте их своевременно.",
              ["kubectl get events -n production --sort-by=.lastTimestamp"], bundledVersion: 2),
        entry("Статус rollout", "kubectl rollout status deployment/<name> -n <namespace>", .kubernetes,
              ["deployment", "rollout"], "Ожидает завершения развёртывания.",
              "Команда завершается успешно только после готовности новой ревизии. Добавьте --timeout, чтобы ограничить ожидание в CI.",
              ["kubectl rollout status deployment/api -n production --timeout=120s"], bundledVersion: 2),
        entry("Откат deployment", "kubectl rollout undo deployment/<name> -n <namespace>", .kubernetes,
              ["deployment", "rollback"], "Возвращает deployment к предыдущей ревизии.",
              "Перед откатом посмотрите rollout history. Флаг --to-revision позволяет выбрать конкретную сохранённую ревизию.",
              ["kubectl rollout history deployment/api -n production\nkubectl rollout undo deployment/api -n production --to-revision=3"], bundledVersion: 2),
        entry("Потребление ресурсов", "kubectl top pods -A --sort-by=cpu", .kubernetes,
              ["metrics", "cpu", "memory"], "Показывает CPU и память подов.",
              "Команда требует Metrics Server. Значения предназначены для оперативной диагностики, а не для долгосрочного мониторинга.",
              ["kubectl top pods -n production --containers --sort-by=memory"], bundledVersion: 2),

        entry("Список releases", "helm list -A", .helm,
              ["release", "list"], "Показывает Helm releases во всех namespace.",
              "По умолчанию видны только deployed и failed releases. Для полной истории используйте --all и при необходимости фильтр --filter.",
              ["helm list -A --all --filter '^api-'"], bundledVersion: 2),
        entry("Установка или обновление", "helm upgrade --install <release> <chart> -n <namespace> --create-namespace", .helm,
              ["upgrade", "install"], "Идемпотентно устанавливает или обновляет release.",
              "Добавьте --atomic, чтобы Helm откатил неуспешное изменение, и --wait для ожидания готовности ресурсов.",
              ["helm upgrade --install api ./chart -n production --create-namespace --atomic --timeout 5m"], bundledVersion: 2),
        entry("Рендер шаблонов", "helm template <release> <chart> -n <namespace>", .helm,
              ["template", "debug"], "Локально рендерит Kubernetes-манифесты без установки.",
              "Полезно для review и отладки values. Команда не проверяет поведение admission webhooks живого кластера.",
              ["helm template api ./chart -n production -f values-prod.yaml --debug > rendered.yaml"], bundledVersion: 2),
        entry("Получить применённые values", "helm get values <release> -n <namespace> -a", .helm,
              ["values", "release"], "Показывает значения действующего release.",
              "Флаг -a добавляет вычисленные значения chart defaults. Без него выводятся только переопределения пользователя.",
              ["helm get values api -n production -a -o yaml"], bundledVersion: 2),
        entry("Проверить chart", "helm lint <chart>", .helm,
              ["lint", "chart"], "Проверяет структуру и шаблоны Helm chart.",
              "Lint выявляет распространённые ошибки до установки. Передавайте те же values, которые будут использоваться в окружении.",
              ["helm lint ./chart -f values-prod.yaml --strict"], bundledVersion: 2),
        entry("Обновить зависимости chart", "helm dependency update <chart>", .helm,
              ["dependency", "chart"], "Скачивает зависимости согласно Chart.yaml.",
              "Команда обновляет Chart.lock. Зафиксированный lock-файл делает сборку chart воспроизводимой.",
              ["helm dependency update ./chart\nhelm dependency build ./chart"], bundledVersion: 2),

        entry("Git sources", "flux get sources git -A", .flux,
              ["source", "git"], "Показывает состояние GitRepository sources.",
              "Проверьте revision, ready и message. Это помогает отделить ошибку получения Git от ошибки применения Kustomization.",
              ["flux get sources git -n flux-system"], bundledVersion: 2),
        entry("Kustomizations", "flux get kustomizations -A", .flux,
              ["kustomization", "status"], "Показывает готовность Flux Kustomizations.",
              "Revision показывает фактически применённый commit. Not ready message обычно содержит первичную причину ошибки build или apply.",
              ["flux get kustomizations -A --status-selector ready=false"], bundledVersion: 2),
        entry("Сверить Git source", "flux reconcile source git <name> -n <namespace>", .flux,
              ["source", "reconcile"], "Немедленно обновляет GitRepository source.",
              "Команда ждёт завершения reconciliation и показывает новую revision. Она не применяет зависимые Kustomizations автоматически вне их интервала.",
              ["flux reconcile source git flux-system -n flux-system"], bundledVersion: 2),
        entry("Приостановить Kustomization", "flux suspend kustomization <name> -n <namespace>", .flux,
              ["suspend", "kustomization"], "Временно отключает reconciliation.",
              "Suspend сохраняет ресурсы в кластере, но Flux перестаёт приводить их к Git-состоянию. Не забудьте выполнить resume.",
              ["flux suspend kustomization apps -n flux-system\nflux resume kustomization apps -n flux-system"], bundledVersion: 2),
        entry("Дерево зависимостей", "flux tree kustomization <name> -n <namespace>", .flux,
              ["tree", "dependencies"], "Показывает ресурсы, управляемые Kustomization.",
              "Дерево удобно для поиска конкретного объекта и понимания inventory, который Flux считает принадлежащим Kustomization.",
              ["flux tree kustomization apps -n flux-system"], bundledVersion: 2),
        entry("Логи Flux controllers", "flux logs --all-namespaces --level=error", .flux,
              ["logs", "controller", "debug"], "Собирает ошибки Flux controllers.",
              "Фильтруйте по kind, name или времени, чтобы уменьшить шум. Вывод берётся из логов controller pods в кластере.",
              ["flux logs --kind=Kustomization --name=apps --since=30m"], bundledVersion: 2),

        entry("Открытые порты", "ss -tulpn", .linux,
              ["network", "ports"], "Показывает слушающие TCP/UDP-сокеты и процессы.",
              "Для имён процессов часто нужны права root. -l оставляет listening, -p добавляет process, -n отключает DNS и service-name lookup.",
              ["sudo ss -ltnp 'sport = :443'"], bundledVersion: 2),
        entry("Логи systemd unit", "journalctl -u <unit> -f", .linux,
              ["systemd", "logs"], "Следит за журналом выбранного systemd unit.",
              "Используйте --since/--until для диапазона времени и -p для приоритета. Ctrl+C завершает follow mode.",
              ["journalctl -u nginx --since '1 hour ago' -p warning"], bundledVersion: 2),
        entry("Крупные файлы", "find <path> -type f -size +1G -print", .linux,
              ["disk", "find"], "Находит файлы больше заданного размера.",
              "Сначала запускайте без удаления. -xdev ограничивает поиск одной файловой системой и не даёт уйти в примонтированные тома.",
              ["sudo find /var -xdev -type f -size +500M -print"], bundledVersion: 2),
        entry("Процессы по памяти", "ps aux --sort=-%mem | head", .linux,
              ["process", "memory"], "Показывает процессы с наибольшим потреблением памяти.",
              "RSS отражает резидентную память, а %MEM — долю физической памяти. Для динамического наблюдения используйте top или htop.",
              ["ps -eo pid,user,%cpu,%mem,rss,command --sort=-rss | head -20"], bundledVersion: 2),
        entry("HTTP-заголовки", "curl -I <url>", .linux,
              ["http", "curl"], "Запрашивает только HTTP-заголовки ответа.",
              "-I отправляет HEAD. Сервер может обрабатывать HEAD иначе, поэтому для точной диагностики GET используйте -D - -o /dev/null.",
              ["curl -sS -D - -o /dev/null https://example.com/health"], bundledVersion: 2),
        entry("Архив tar.gz", "tar -czf <archive.tar.gz> <path>", .linux,
              ["archive", "tar"], "Создаёт gzip-сжатый tar-архив.",
              "Перед распаковкой незнакомого архива сначала просмотрите содержимое. -C задаёт безопасный целевой каталог.",
              ["tar -tzf backup.tar.gz\ntar -xzf backup.tar.gz -C ./restore"], bundledVersion: 2),

        entry("Проверить inventory", "ansible-inventory -i <inventory> --graph", .ansible,
              ["inventory", "graph"], "Показывает группы и hosts inventory.",
              "Команда помогает проверить наследование групп до запуска playbook. --host выводит вычисленные переменные конкретного host.",
              ["ansible-inventory -i inventory.yml --host web-01"], bundledVersion: 2),
        entry("Проверить доступность", "ansible all -i <inventory> -m ping", .ansible,
              ["ping", "connectivity"], "Проверяет подключение и Python на managed nodes.",
              "Ansible ping не использует ICMP: модуль подключается через configured connection и выполняет Python-код.",
              ["ansible web -i inventory.yml -m ping -u deploy"], bundledVersion: 2),
        entry("Проверить синтаксис", "ansible-playbook <playbook.yml> --syntax-check", .ansible,
              ["syntax", "playbook"], "Проверяет синтаксис playbook без выполнения tasks.",
              "Проверка не обнаруживает все runtime-ошибки переменных и модулей. Дополните её --list-tasks и check mode.",
              ["ansible-playbook site.yml -i inventory.yml --syntax-check"], bundledVersion: 2),
        entry("Запустить выбранные tags", "ansible-playbook <playbook.yml> --tags '<tags>'", .ansible,
              ["tags", "select"], "Ограничивает выполнение задач заданными tags.",
              "Перед запуском проверьте доступные tags через --list-tags. Несколько tags разделяются запятыми.",
              ["ansible-playbook site.yml --list-tags\nansible-playbook site.yml --tags 'config,restart'"], bundledVersion: 2),
        entry("Зашифровать файл Vault", "ansible-vault encrypt <file>", .ansible,
              ["vault", "secrets"], "Шифрует файл для хранения секретов в репозитории.",
              "Не передавайте пароль прямо в командной строке. Используйте prompt или защищённый password file с подходящими permissions.",
              ["ansible-vault encrypt group_vars/production/vault.yml\nansible-vault view group_vars/production/vault.yml"], bundledVersion: 2),
        entry("Ad-hoc команда", "ansible <pattern> -i <inventory> -m command -a '<command>'", .ansible,
              ["adhoc", "command"], "Выполняет одноразовую команду на выбранных hosts.",
              "Модуль command не обрабатывает shell-конвейеры и перенаправления, что безопаснее. Для повторяемых изменений создайте playbook.",
              ["ansible web -i inventory.yml -m command -a 'uptime'"], bundledVersion: 2),

        entry("Инициализация", "terraform init", .terraform,
              ["init", "providers"], "Инициализирует backend, providers и modules.",
              "После изменения constraints используйте -upgrade осознанно и проверяйте обновившийся lock-файл. -reconfigure меняет backend без миграции state.",
              ["terraform init -upgrade\nterraform providers"], bundledVersion: 2),
        entry("Проверка конфигурации", "terraform validate", .terraform,
              ["validate", "hcl"], "Проверяет внутреннюю согласованность Terraform-конфигурации.",
              "Validate не обращается к remote APIs, но требует предварительного terraform init. Он не заменяет plan.",
              ["terraform init -backend=false\nterraform validate -json"], bundledVersion: 2),
        entry("Список state", "terraform state list", .terraform,
              ["state", "resources"], "Перечисляет адреса ресурсов в state.",
              "Команды state работают с критичными данными. Перед изменяющими операциями сделайте резервную копию и используйте точные адреса.",
              ["terraform state list 'module.network.*'\nterraform state show module.network.aws_vpc.main"], bundledVersion: 2),
        entry("Outputs в JSON", "terraform output -json", .terraform,
              ["output", "json"], "Выводит outputs в машиночитаемом формате.",
              "Sensitive outputs всё равно присутствуют в JSON. Не отправляйте вывод в логи CI и не сохраняйте его в открытых артефактах.",
              ["terraform output -json endpoint | jq -r '.'"], bundledVersion: 2),
        entry("Рабочие пространства", "terraform workspace list", .terraform,
              ["workspace", "state"], "Показывает Terraform workspaces текущего backend.",
              "Workspace разделяет state, но не является полной изоляцией окружений. Текущий workspace отмечен звёздочкой.",
              ["terraform workspace select staging\nterraform workspace show"], bundledVersion: 2),
        entry("Зафиксировать providers", "terraform providers lock", .terraform,
              ["providers", "lock"], "Обновляет checksums в dependency lock file.",
              "Зафиксируйте хеши нужных платформ, если plan выполняется на macOS, а apply — на Linux CI.",
              ["terraform providers lock -platform=darwin_arm64 -platform=linux_amd64"], bundledVersion: 2)
    ]
}
