enum AnsibleCatalog {
    static let entries: [CommandEntry] = [
        BundledCatalogEntry.make("Проверить playbook", "ansible-playbook <playbook.yml> --check --diff", .ansible,
              ["check", "dry-run"], "Показывает предполагаемые изменения playbook.",
              "Check mode не гарантирует отсутствие побочных эффектов для модулей без полной поддержки check mode. --diff показывает изменения файлов.",
              ["ansible-playbook site.yml -i inventory --check --diff"]),
        BundledCatalogEntry.make("Ограничить hosts", "ansible-playbook <playbook.yml> --limit '<pattern>'", .ansible,
              ["limit", "hosts"], "Запускает playbook только для выбранных hosts.",
              "Pattern сопоставляется с inventory. Перед реальным запуском полезно проверить выбор через ansible --list-hosts.",
              ["ansible all -i inventory --list-hosts --limit 'web:&production'"]),
        BundledCatalogEntry.make("Проверить inventory", "ansible-inventory -i <inventory> --graph", .ansible,
              ["inventory", "graph"], "Показывает группы и hosts inventory.",
              "Команда помогает проверить наследование групп до запуска playbook. --host выводит вычисленные переменные конкретного host.",
              ["ansible-inventory -i inventory.yml --host web-01"], bundledVersion: 2),
        BundledCatalogEntry.make("Проверить доступность", "ansible all -i <inventory> -m ping", .ansible,
              ["ping", "connectivity"], "Проверяет подключение и Python на managed nodes.",
              "Ansible ping не использует ICMP: модуль подключается через configured connection и выполняет Python-код.",
              ["ansible web -i inventory.yml -m ping -u deploy"], bundledVersion: 2),
        BundledCatalogEntry.make("Проверить синтаксис", "ansible-playbook <playbook.yml> --syntax-check", .ansible,
              ["syntax", "playbook"], "Проверяет синтаксис playbook без выполнения tasks.",
              "Проверка не обнаруживает все runtime-ошибки переменных и модулей. Дополните её --list-tasks и check mode.",
              ["ansible-playbook site.yml -i inventory.yml --syntax-check"], bundledVersion: 2),
        BundledCatalogEntry.make("Запустить выбранные tags", "ansible-playbook <playbook.yml> --tags '<tags>'", .ansible,
              ["tags", "select"], "Ограничивает выполнение задач заданными tags.",
              "Перед запуском проверьте доступные tags через --list-tags. Несколько tags разделяются запятыми.",
              ["ansible-playbook site.yml --list-tags\nansible-playbook site.yml --tags 'config,restart'"], bundledVersion: 2),
        BundledCatalogEntry.make("Зашифровать файл Vault", "ansible-vault encrypt <file>", .ansible,
              ["vault", "secrets"], "Шифрует файл для хранения секретов в репозитории.",
              "Не передавайте пароль прямо в командной строке. Используйте prompt или защищённый password file с подходящими permissions.",
              ["ansible-vault encrypt group_vars/production/vault.yml\nansible-vault view group_vars/production/vault.yml"], bundledVersion: 2),
        BundledCatalogEntry.make("Ad-hoc команда", "ansible <pattern> -i <inventory> -m command -a '<command>'", .ansible,
              ["adhoc", "command"], "Выполняет одноразовую команду на выбранных hosts.",
              "Модуль command не обрабатывает shell-конвейеры и перенаправления, что безопаснее. Для повторяемых изменений создайте playbook.",
              ["ansible web -i inventory.yml -m command -a 'uptime'"], bundledVersion: 2)
    ]
}
