enum FluxCatalog {
    static let entries: [CommandEntry] = [
        BundledCatalogEntry.make("Состояние Flux", "flux get all -A", .flux,
              ["status", "reconcile"], "Показывает состояние ресурсов Flux.",
              "Вывод объединяет основные Flux controllers и помогает найти suspended или not ready ресурсы.",
              ["flux get all -A --status-selector ready=false"]),
        BundledCatalogEntry.make("Принудительная сверка", "flux reconcile kustomization <name> -n <namespace> --with-source", .flux,
              ["reconcile", "kustomization"], "Запускает reconciliation немедленно.",
              "Флаг --with-source сначала обновляет связанный source, затем применяет Kustomization.",
              ["flux reconcile kustomization apps -n flux-system --with-source"]),
        BundledCatalogEntry.make("Git sources", "flux get sources git -A", .flux,
              ["source", "git"], "Показывает состояние GitRepository sources.",
              "Проверьте revision, ready и message. Это помогает отделить ошибку получения Git от ошибки применения Kustomization.",
              ["flux get sources git -n flux-system"], bundledVersion: 2),
        BundledCatalogEntry.make("Kustomizations", "flux get kustomizations -A", .flux,
              ["kustomization", "status"], "Показывает готовность Flux Kustomizations.",
              "Revision показывает фактически применённый commit. Not ready message обычно содержит первичную причину ошибки build или apply.",
              ["flux get kustomizations -A --status-selector ready=false"], bundledVersion: 2),
        BundledCatalogEntry.make("Сверить Git source", "flux reconcile source git <name> -n <namespace>", .flux,
              ["source", "reconcile"], "Немедленно обновляет GitRepository source.",
              "Команда ждёт завершения reconciliation и показывает новую revision. Она не применяет зависимые Kustomizations автоматически вне их интервала.",
              ["flux reconcile source git flux-system -n flux-system"], bundledVersion: 2),
        BundledCatalogEntry.make("Приостановить Kustomization", "flux suspend kustomization <name> -n <namespace>", .flux,
              ["suspend", "kustomization"], "Временно отключает reconciliation.",
              "Suspend сохраняет ресурсы в кластере, но Flux перестаёт приводить их к Git-состоянию. Не забудьте выполнить resume.",
              ["flux suspend kustomization apps -n flux-system\nflux resume kustomization apps -n flux-system"], bundledVersion: 2),
        BundledCatalogEntry.make("Дерево зависимостей", "flux tree kustomization <name> -n <namespace>", .flux,
              ["tree", "dependencies"], "Показывает ресурсы, управляемые Kustomization.",
              "Дерево удобно для поиска конкретного объекта и понимания inventory, который Flux считает принадлежащим Kustomization.",
              ["flux tree kustomization apps -n flux-system"], bundledVersion: 2),
        BundledCatalogEntry.make("Логи Flux controllers", "flux logs --all-namespaces --level=error", .flux,
              ["logs", "controller", "debug"], "Собирает ошибки Flux controllers.",
              "Фильтруйте по kind, name или времени, чтобы уменьшить шум. Вывод берётся из логов controller pods в кластере.",
              ["flux logs --kind=Kustomization --name=apps --since=30m"], bundledVersion: 2)
    ]
}
