enum HelmCatalog {
    static let entries: [CommandEntry] = [
        BundledCatalogEntry.make("Обновить репозитории", "helm repo update", .helm,
              ["repo", "update"], "Обновляет локальный индекс Helm-репозиториев.",
              "Команда скачивает актуальные индексы уже добавленных репозиториев, но не обновляет установленные releases.",
              ["helm repo list\nhelm repo update"]),
        BundledCatalogEntry.make("История release", "helm history <release> -n <namespace>", .helm,
              ["release", "rollback"], "Показывает ревизии Helm release.",
              "В истории видны номера ревизий и их статусы. Номер можно передать в helm rollback.",
              ["helm history ingress-nginx -n ingress\nhelm rollback ingress-nginx 2 -n ingress"]),
        BundledCatalogEntry.make("Список releases", "helm list -A", .helm,
              ["release", "list"], "Показывает Helm releases во всех namespace.",
              "По умолчанию видны только deployed и failed releases. Для полной истории используйте --all и при необходимости фильтр --filter.",
              ["helm list -A --all --filter '^api-'"], bundledVersion: 2),
        BundledCatalogEntry.make("Установка или обновление", "helm upgrade --install <release> <chart> -n <namespace> --create-namespace", .helm,
              ["upgrade", "install"], "Идемпотентно устанавливает или обновляет release.",
              "Добавьте --atomic, чтобы Helm откатил неуспешное изменение, и --wait для ожидания готовности ресурсов.",
              ["helm upgrade --install api ./chart -n production --create-namespace --atomic --timeout 5m"], bundledVersion: 2),
        BundledCatalogEntry.make("Рендер шаблонов", "helm template <release> <chart> -n <namespace>", .helm,
              ["template", "debug"], "Локально рендерит Kubernetes-манифесты без установки.",
              "Полезно для review и отладки values. Команда не проверяет поведение admission webhooks живого кластера.",
              ["helm template api ./chart -n production -f values-prod.yaml --debug > rendered.yaml"], bundledVersion: 2),
        BundledCatalogEntry.make("Получить применённые values", "helm get values <release> -n <namespace> -a", .helm,
              ["values", "release"], "Показывает значения действующего release.",
              "Флаг -a добавляет вычисленные значения chart defaults. Без него выводятся только переопределения пользователя.",
              ["helm get values api -n production -a -o yaml"], bundledVersion: 2),
        BundledCatalogEntry.make("Проверить chart", "helm lint <chart>", .helm,
              ["lint", "chart"], "Проверяет структуру и шаблоны Helm chart.",
              "Lint выявляет распространённые ошибки до установки. Передавайте те же values, которые будут использоваться в окружении.",
              ["helm lint ./chart -f values-prod.yaml --strict"], bundledVersion: 2),
        BundledCatalogEntry.make("Обновить зависимости chart", "helm dependency update <chart>", .helm,
              ["dependency", "chart"], "Скачивает зависимости согласно Chart.yaml.",
              "Команда обновляет Chart.lock. Зафиксированный lock-файл делает сборку chart воспроизводимой.",
              ["helm dependency update ./chart\nhelm dependency build ./chart"], bundledVersion: 2)
    ]
}
