enum KubernetesCatalog {
    static let entries: [CommandEntry] = [
        BundledCatalogEntry.make("Поды во всех namespace", "kubectl get pods -A", .kubernetes,
              ["pods", "list"], "Показывает все поды кластера.",
              "Флаг -A — сокращение для --all-namespaces. Полезно для быстрого обзора состояния workload во всём кластере.",
              ["kubectl get pods -A -o wide"]),
        BundledCatalogEntry.make("Логи контейнера", "kubectl logs -f <pod> -n <namespace>", .kubernetes,
              ["logs", "debug"], "Показывает и продолжает выводить логи пода.",
              "Флаг -f следит за новым выводом. Если в поде несколько контейнеров, добавьте -c <container>.",
              ["kubectl logs -f api-7d9c -n production -c api"]),
        BundledCatalogEntry.make("Описание ресурса", "kubectl describe <resource> <name> -n <namespace>", .kubernetes,
              ["describe", "debug"], "Показывает состояние, события и параметры ресурса.",
              "Describe объединяет спецификацию, текущее состояние и связанные события. Часто это первый шаг при Pending, CrashLoopBackOff или ошибках scheduling.",
              ["kubectl describe pod api-7d9c -n production"], bundledVersion: 2),
        BundledCatalogEntry.make("Выполнить команду в контейнере", "kubectl exec -it <pod> -n <namespace> -- <command>", .kubernetes,
              ["exec", "shell"], "Запускает процесс внутри работающего контейнера.",
              "Разделитель -- отделяет аргументы kubectl от запускаемой команды. Для нескольких контейнеров укажите -c. Образ может не содержать shell.",
              ["kubectl exec -it api-7d9c -n production -c api -- sh"], bundledVersion: 2),
        BundledCatalogEntry.make("События по времени", "kubectl get events -A --sort-by=.metadata.creationTimestamp", .kubernetes,
              ["events", "debug"], "Сортирует события кластера от старых к новым.",
              "События помогают найти ошибки образов, probes, volumes и scheduler. Старые события удаляются кластером, поэтому проверяйте их своевременно.",
              ["kubectl get events -n production --sort-by=.lastTimestamp"], bundledVersion: 2),
        BundledCatalogEntry.make("Статус rollout", "kubectl rollout status deployment/<name> -n <namespace>", .kubernetes,
              ["deployment", "rollout"], "Ожидает завершения развёртывания.",
              "Команда завершается успешно только после готовности новой ревизии. Добавьте --timeout, чтобы ограничить ожидание в CI.",
              ["kubectl rollout status deployment/api -n production --timeout=120s"], bundledVersion: 2),
        BundledCatalogEntry.make("Откат deployment", "kubectl rollout undo deployment/<name> -n <namespace>", .kubernetes,
              ["deployment", "rollback"], "Возвращает deployment к предыдущей ревизии.",
              "Перед откатом посмотрите rollout history. Флаг --to-revision позволяет выбрать конкретную сохранённую ревизию.",
              ["kubectl rollout history deployment/api -n production\nkubectl rollout undo deployment/api -n production --to-revision=3"], bundledVersion: 2),
        BundledCatalogEntry.make("Потребление ресурсов", "kubectl top pods -A --sort-by=cpu", .kubernetes,
              ["metrics", "cpu", "memory"], "Показывает CPU и память подов.",
              "Команда требует Metrics Server. Значения предназначены для оперативной диагностики, а не для долгосрочного мониторинга.",
              ["kubectl top pods -n production --containers --sort-by=memory"], bundledVersion: 2)
    ]
}
