enum LinuxCatalog {
    static let entries: [CommandEntry] = [
        BundledCatalogEntry.make("Занятое место", "du -sh ./* | sort -h", .linux,
              ["disk", "files"], "Сортирует элементы каталога по размеру.",
              "du вычисляет размер, -s суммирует каждый аргумент, -h выводит читаемые единицы. sort -h понимает эти единицы.",
              ["du -sh /var/log/* | sort -h"]),
        BundledCatalogEntry.make("Поиск текста", "grep -RIn --exclude-dir=.git '<text>' .", .linux,
              ["search", "grep"], "Рекурсивно ищет текст в файлах.",
              "-R следует по дереву, -I пропускает бинарные файлы, -n показывает строку. Значение в кавычках может содержать пробелы.",
              ["grep -RIn --exclude-dir=.git 'listen 443' /etc"]),
        BundledCatalogEntry.make("Открытые порты", "ss -tulpn", .linux,
              ["network", "ports"], "Показывает слушающие TCP/UDP-сокеты и процессы.",
              "Для имён процессов часто нужны права root. -l оставляет listening, -p добавляет process, -n отключает DNS и service-name lookup.",
              ["sudo ss -ltnp 'sport = :443'"], bundledVersion: 2),
        BundledCatalogEntry.make("Логи systemd unit", "journalctl -u <unit> -f", .linux,
              ["systemd", "logs"], "Следит за журналом выбранного systemd unit.",
              "Используйте --since/--until для диапазона времени и -p для приоритета. Ctrl+C завершает follow mode.",
              ["journalctl -u nginx --since '1 hour ago' -p warning"], bundledVersion: 2),
        BundledCatalogEntry.make("Крупные файлы", "find <path> -type f -size +1G -print", .linux,
              ["disk", "find"], "Находит файлы больше заданного размера.",
              "Сначала запускайте без удаления. -xdev ограничивает поиск одной файловой системой и не даёт уйти в примонтированные тома.",
              ["sudo find /var -xdev -type f -size +500M -print"], bundledVersion: 2),
        BundledCatalogEntry.make("Процессы по памяти", "ps aux --sort=-%mem | head", .linux,
              ["process", "memory"], "Показывает процессы с наибольшим потреблением памяти.",
              "RSS отражает резидентную память, а %MEM — долю физической памяти. Для динамического наблюдения используйте top или htop.",
              ["ps -eo pid,user,%cpu,%mem,rss,command --sort=-rss | head -20"], bundledVersion: 2),
        BundledCatalogEntry.make("HTTP-заголовки", "curl -I <url>", .linux,
              ["http", "curl"], "Запрашивает только HTTP-заголовки ответа.",
              "-I отправляет HEAD. Сервер может обрабатывать HEAD иначе, поэтому для точной диагностики GET используйте -D - -o /dev/null.",
              ["curl -sS -D - -o /dev/null https://example.com/health"], bundledVersion: 2),
        BundledCatalogEntry.make("Архив tar.gz", "tar -czf <archive.tar.gz> <path>", .linux,
              ["archive", "tar"], "Создаёт gzip-сжатый tar-архив.",
              "Перед распаковкой незнакомого архива сначала просмотрите содержимое. -C задаёт безопасный целевой каталог.",
              ["tar -tzf backup.tar.gz\ntar -xzf backup.tar.gz -C ./restore"], bundledVersion: 2)
    ]
}
