enum LinuxCatalog {
    static let entries: [CommandEntry] = [
        BundledCatalogEntry.make("Занятое место", "du -sh ./* | sort -h", .linux,
              ["disk", "files"], "Сортирует элементы каталога по размеру.",
              "du вычисляет размер, -s суммирует каждый аргумент, -h выводит читаемые единицы. sort -h понимает эти единицы.",
              ["du -sh /var/log/* | sort -h"]),
        BundledCatalogEntry.make("Поиск текста", "grep -RIn --exclude-dir=.git '<text>' .", .linux,
              ["search", "grep"], "Рекурсивно ищет текст в файлах.",
              "-R следует по дереву, -I пропускает бинарные файлы, -n показывает строку. Значение в кавычках может содержать пробелы.",
              ["grep -RIn --exclude-dir=.git 'listen 443' /etc"]),
        BundledCatalogEntry.make("Открытые порты", "ss -tulpn", .linux,
              ["network", "ports"], "Показывает слушающие TCP/UDP-сокеты и процессы.",
              "Для имён процессов часто нужны права root. -l оставляет listening, -p добавляет process, -n отключает DNS и service-name lookup.",
              ["sudo ss -ltnp 'sport = :443'"], bundledVersion: 2),
        BundledCatalogEntry.make("Логи systemd unit", "journalctl -u <unit> -f", .linux,
              ["systemd", "logs"], "Следит за журналом выбранного systemd unit.",
              "Используйте --since/--until для диапазона времени и -p для приоритета. Ctrl+C завершает follow mode.",
              ["journalctl -u nginx --since '1 hour ago' -p warning"], bundledVersion: 2),
        BundledCatalogEntry.make("Крупные файлы", "find <path> -type f -size +1G -print", .linux,
              ["disk", "find"], "Находит файлы больше заданного размера.",
              "Сначала запускайте без удаления. -xdev ограничивает поиск одной файловой системой и не даёт уйти в примонтированные тома.",
              ["sudo find /var -xdev -type f -size +500M -print"], bundledVersion: 2),
        BundledCatalogEntry.make("Процессы по памяти", "ps aux --sort=-%mem | head", .linux,
              ["process", "memory"], "Показывает процессы с наибольшим потреблением памяти.",
              "RSS отражает резидентную память, а %MEM — долю физической памяти. Для динамического наблюдения используйте top или htop.",
              ["ps -eo pid,user,%cpu,%mem,rss,command --sort=-rss | head -20"], bundledVersion: 2),
        BundledCatalogEntry.make("HTTP-заголовки", "curl -I <url>", .linux,
              ["http", "curl"], "Запрашивает только HTTP-заголовки ответа.",
              "-I отправляет HEAD. Сервер может обрабатывать HEAD иначе, поэтому для точной диагностики GET используйте -D - -o /dev/null.",
              ["curl -sS -D - -o /dev/null https://example.com/health"], bundledVersion: 2),
        BundledCatalogEntry.make("Архив tar.gz", "tar -czf <archive.tar.gz> <path>", .linux,
               ["archive", "tar"], "Создаёт gzip-сжатый tar-архив.",
               "Перед распаковкой незнакомого архива сначала просмотрите содержимое. -C задаёт безопасный целевой каталог.",
               ["tar -tzf backup.tar.gz\ntar -xzf backup.tar.gz -C ./restore"], bundledVersion: 2),
        BundledCatalogEntry.make("Поиск файлов по имени", "find <path> -name '<pattern>'", .linux,
               ["find", "files"], "Ищет файлы по маске имени.",
               "-iname делает поиск нечувствительным к регистру. Используйте -type d для поиска только директорий.",
               ["find /etc -name '*.conf'", "find . -iname '*backup*'"], bundledVersion: 3),
        BundledCatalogEntry.make("Анализ нагрузки (CPU)", "top -bn1 | grep 'Cpu(s)'", .linux,
               ["process", "cpu", "load"], "Показывает текущее использование CPU в одну строку.",
               "top -b переводит вывод в пакетный режим, что позволяет фильтровать его через grep. Полезно для скриптов мониторинга.",
               ["top -bn1 | grep 'Cpu(s)'"], bundledVersion: 3),
        BundledCatalogEntry.make("Проверка прав доступа", "getfacl <path>", .linux,
               ["permissions", "acl"], "Показывает детальные права доступа (ACL) к файлу или папке.",
               "В отличие от ls -l, getfacl показывает расширенные списки управления доступом. Для изменения прав используйте setfacl.",
               ["getfacl /var/www/html"], bundledVersion: 3),
        BundledCatalogEntry.make("Слежение за открытыми файлами", "lsof -p <pid>", .linux,
               ["process", "files"], "Показывает все файлы, открытые конкретным процессом.",
               "lsof (list open files) помогает понять, какой процесс держит файл или какой сокет открыт. -i показывает сетевые соединения.",
               ["sudo lsof -i :80", "sudo lsof -p 1234"], bundledVersion: 3),
        BundledCatalogEntry.make("Проверка доступности порта", "nc -zv <host> <port>", .linux,
               ["network", "port", "nc"], "Проверяет, открыт ли TCP/UDP порт на удаленном хосте.",
               "nc (netcat) — 'швейцарский нож' сетевика. -z запрещает отправку данных, -v включает подробный вывод.",
               ["nc -zv google.com 443", "nc -zuv 192.168.1.1 53"], bundledVersion: 3),
        BundledCatalogEntry.make("Просмотр последних строк лога", "tail -n <count> <file>", .linux,
               ["logs", "tail"], "Выводит последние N строк файла.",
               "Используйте -f для слежения за логом в реальном времени (аналог journalctl -f для текстовых файлов).",
               ["tail -n 100 /var/log/syslog", "tail -f /var/log/nginx/error.log"], bundledVersion: 3)
    ]
}
