enum TerraformCatalog {
    static let entries: [CommandEntry] = [
        BundledCatalogEntry.make("План изменений", "terraform plan -out=tfplan", .terraform,
              ["plan", "safe"], "Создаёт и сохраняет план Terraform.",
              "Сохранённый plan позволяет применить именно просмотренный набор изменений командой terraform apply tfplan.",
              ["terraform plan -out=tfplan\nterraform apply tfplan"]),
        BundledCatalogEntry.make("Форматирование конфигурации", "terraform fmt -recursive", .terraform,
              ["fmt", "hcl"], "Форматирует Terraform-файлы рекурсивно.",
              "Команда изменяет файлы на месте в канонический формат. Перед commit проверьте diff.",
              ["terraform fmt -check -recursive"]),
        BundledCatalogEntry.make("Инициализация", "terraform init", .terraform,
              ["init", "providers"], "Инициализирует backend, providers и modules.",
              "После изменения constraints используйте -upgrade осознанно и проверяйте обновившийся lock-файл. -reconfigure меняет backend без миграции state.",
              ["terraform init -upgrade\nterraform providers"], bundledVersion: 2),
        BundledCatalogEntry.make("Проверка конфигурации", "terraform validate", .terraform,
              ["validate", "hcl"], "Проверяет внутреннюю согласованность Terraform-конфигурации.",
              "Validate не обращается к remote APIs, но требует предварительного terraform init. Он не заменяет plan.",
              ["terraform init -backend=false\nterraform validate -json"], bundledVersion: 2),
        BundledCatalogEntry.make("Список state", "terraform state list", .terraform,
              ["state", "resources"], "Перечисляет адреса ресурсов в state.",
              "Команды state работают с критичными данными. Перед изменяющими операциями сделайте резервную копию и используйте точные адреса.",
              ["terraform state list 'module.network.*'\nterraform state show module.network.aws_vpc.main"], bundledVersion: 2),
        BundledCatalogEntry.make("Outputs в JSON", "terraform output -json", .terraform,
              ["output", "json"], "Выводит outputs в машиночитаемом формате.",
              "Sensitive outputs всё равно присутствуют в JSON. Не отправляйте вывод в логи CI и не сохраняйте его в открытых артефактах.",
              ["terraform output -json endpoint | jq -r '.'"], bundledVersion: 2),
        BundledCatalogEntry.make("Рабочие пространства", "terraform workspace list", .terraform,
              ["workspace", "state"], "Показывает Terraform workspaces текущего backend.",
              "Workspace разделяет state, но не является полной изоляцией окружений. Текущий workspace отмечен звёздочкой.",
              ["terraform workspace select staging\nterraform workspace show"], bundledVersion: 2),
        BundledCatalogEntry.make("Зафиксировать providers", "terraform providers lock", .terraform,
              ["providers", "lock"], "Обновляет checksums в dependency lock file.",
              "Зафиксируйте хеши нужных платформ, если plan выполняется на macOS, а apply — на Linux CI.",
              ["terraform providers lock -platform=darwin_arm64 -platform=linux_amd64"], bundledVersion: 2)
    ]
}
